{% set name = "bilby_pipe" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9335ff85988e85c80ac4b63189648d15b6f5141ad8288cc863dad570441ca2aa

build:
  number: 0
  noarch: python
  entry_points:
    - bilby_pipe = bilby_pipe.main:main
    - bilby_pipe_generation = bilby_pipe.data_generation:main
    - bilby_pipe_analysis = bilby_pipe.data_analysis:main
    - bilby_pipe_create_injection_file = bilby_pipe.create_injections:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - bilby >=0.4.1
    - configargparse
    - future
    - gwpy
    - ligo-gracedb
    - matplotlib-base
    - numpy
    - pesummary
    - pycondor >=0.5
    - python >=3.5
    - scipy >=1.2.0
    - tqdm

test:
  imports:
    - bilby_pipe
  commands:
    - bilby_pipe --help
    - bilby_pipe_generation --help
    - bilby_pipe_analysis --help
    - bilby_pipe_create_injection_file --help

about:
  home: https://lscsoft.docs.ligo.org/bilby_pipe/
  doc_url: https://lscsoft.docs.ligo.org/bilby_pipe/
  dev_url: https://git.ligo.org/lscsoft/bilby_pipe/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automating the running of bilby for gravitational wave signals
  description: |
    A package for automating transient gravitational wave parameter estimation

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GregoryAshton
