travis:
  secure:
    BINSTAR_TOKEN: c7vHMQzZNspEioz14m7DNNRWdF5yHgWRhkBmAu+C1wLzHHdMKJUQBDtjQsZ2agNj7amHLFTwo+J31Z5ADEl3yveLthP9qtLcTenZ7EcAP180/dOGEC6eVz8OvsJqurtTtrBlGTel3/C9qjMJQzbQCXjKG4hg0goOMTVenbcGN5wd6o8mB3H026zEbLhlKryI+qihdv1FOwpBDjoGLeSeDpl+SdGzS8JOCJuIPWmbPYMiuo/lJvdAGeAvs5LcrZ3OI3STi7XeKUuX3JOPCfJWM9oxBRNM98o+OEiFSJFgbQugQPjf/rQNOXM8mZbBFwc1dXqR1B3IsF1qvdzNsmogsZm/4VmNAd/RxnOuSIuk4eISslW0geCe9uShymP/+6CY0v7VMru+UX/ACekkL+AwzU1hmTADP+/CFNLZenDnvrZCc22djrpACZ+R4rj//4gImPK4454mnSCC13H8CRkvS/y4eyRhD3Mn5bZmNwh/uicnGMd00Sbdkh6vDdTYoMeyId71bCmBAfb3EH3cjD31J3zgsWSxYv2QtBgfT/W4rQ7wihabVRg2udkvMEJVoH1jc9rpeVkZZTNqQx+ADuTGQhyAtuUCaHR4pVlfRQovHqisYa0BXsCluYYBg7chwW8URnh4dsfrsBoZPHNpo2p+yl8vqG3HlWn99fWeBTtCGlg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
